name: heart_disease_predictor
dependencies:
  - pandas=1.3.5
  - scipy=1.7.1
  - seaborn=0.11.2
  - scikit-learn=0.24.0
  - tensorflow==2.4.0
  - xgboost
  - plotly.express
  - pip:
    - ipython==8.10.0
    - matplotlib==3.5.3
    - jupyter==1.0.0
